apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "dGhpc2lzc29tZXRoaW5ndG9iZWhvbGQK"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: aXNhYWM= 
  postgres-password: cmVkZWVtZXI=

#kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json