apiVersion: v1
kind: ConfigMap
metadata:
  name: utterzone-config
data:
  config.json: |
    {
      "environment" : "production"
    }
# kubectl create configmap example-config --from-file ./golang/configs/config.json
